### ISSUE TITLE
Написать лекцию о функциях

### ISSUE THREAD

**Issue by ch3rn0v** [open-data-science/pycourse#19]
Написать лекцию о функциях в base/functions/ . Описать, что это, какие они бывают, какие функции когда и как использовать. Рассказать об особенностях их реализации в питоне, неочевидном поведении и тому, к каким последствиям это может привести.

**Comment by vvssttkk** [comment]
@ch3rn0v не хотите сами взяться?

**Comment by ch3rn0v** [comment]
@vvssttkk готов взяться. Не вижу возможности назначить на себя, возможно, нет таких прав. Если у вас есть, назначьте, пожалуйста.

**Comment by vvssttkk** [comment]
вы видели #13?

**Comment by vvssttkk** [comment]
вдобавок вот [contributing.md](https://github.com/open-data-science/pycourse/blob/master/contributing.md)

**Comment by ch3rn0v** [comment]
Да, contributing прочитал (включая обновление). По поводу #13 - видел, что там о функциях уже рассказано, хотя и в контексте другого курса. А здесь, как я понимаю, планируется фокус именно на питоне. Кроме того, некоторые вещи я бы изложил иначе, например:

>в return можно перечислять несколько возвращаемых значений через запятую

Я бы явно сказал, что в питоне возвращаемое значение у функции всегда одно; `return ret_val_a, ret_val_b` тоже является возвращением одного значения - кортежа из двух элементов. Тут же можно рассказать и о деструктуризации.
Дополнительно я бы рассказал о чистых функциях и сайд эффектах. И в целом пошел бы от общего к частному, от простого к сложному, и по возможности на примере одной (постепенно дорабатываемой) функции, потому что так проще увидеть разницу и результат нововведений.

Поэтому предлагаю так - я допишу свою версию, покажу, и решим, что в итоге оставить, что убрать. Думаю, до 20 сентября успею с первой версией.

**Comment by vvssttkk** [comment]
> хотя и в контексте другого курса

он переносится оттуда и бужей началом этого курса

за основу можете взять что уже есть в https://github.com/quantum-ods/qmlcourse/blob/master/qmlcourse/book/python/ru/python_l8.md и дополнить от себя

**Comment by vvssttkk** [comment]
доделал стилистику как хотел

@ch3rn0v добавил вас в авторы курса (примите заявку), теперь не нужно создавать fork, а сразу делать изменения в ветках, как и создавать их (если что-то не так, отпишите)

в #22 можете добавить от себя ещё что хотите

**Comment by ch3rn0v** [comment]
Спасибо, заявку принял, про изменения понял.

Изучу обновленную стилистику и затем допишу еще про функции

**Comment by vvssttkk** [comment]
@ch3rn0v когда планируете добавлять что хотели в pr? если нет времени, предлагаю #22 влить в master и что хотели сделать создать новый issue

**Comment by ch3rn0v** [comment]
@vvssttkk , пока не успел, да. Давайте тогда новый issue создам и назначу на себя
