### ISSUE TITLE
написать о `match/case` и `контекстном менеджере в скобках`

### ISSUE THREAD

**Issue by vvssttkk** [open-data-science/pycourse#37]
продолжение #10 

добавить в лекцию «условия и сравнения»

- [ ] [match/case](https://docs.python.org/3/whatsnew/3.10.html#pep-634-structural-pattern-matching)
- [ ] [контекстном менеджере в скобках](https://docs.python.org/3/whatsnew/3.10.html#parenthesized-context-managers)

**Comment by e0xextazy** [comment]
Еще добавлю про обычный контекстный менедер, чтобы от него перейти к менеджерам в круглых скобках

**Comment by e0xextazy** [comment]
Стоит ли добавлять про самописные протоколы для контексного менеджера?

**Comment by vvssttkk** [comment]
> Стоит ли добавлять про самописные протоколы для контексного менеджера?

частично можно упомянуть, но детальнее в другом разделе как-то будет
