### ISSUE TITLE
Рефакторинг всего существующего кода в лекциях

### ISSUE THREAD

**Issue by e0xextazy** [open-data-science/pycourse#45]
Проверить весь код и привести его к единственному стилю

**Comment by vvssttkk** [comment]
опиши кратко этот стиль, дабы было понятно что да как (как мин поможет проверять эту задачу)

**Comment by e0xextazy** [comment]
![Снимок экрана 2022-10-07 в 16 14 08](https://user-images.githubusercontent.com/49094658/194562263-431aa820-9e80-4276-8a8c-8de588a6dfe7.png)

**Comment by vvssttkk** [comment]
и это всё?
